### ISSUE TITLE
Exploting when ingresas ecuacion X^2+5-1=x

### ISSUE THREAD

**Issue by leacoder** [agustinsilva/profebot#12]
Log error :
![image](https://user-images.githubusercontent.com/4481229/45462616-0608c380-b6df-11e8-8b58-2358ec9ffa0c.png)

**Comment by ezebor** [comment]
@Zaxtor para mi, debería dejar el polinomio sin factorizar. En cuyo caso, sería como poner una expresión que el resolutor no maneja, por ejemplo cúbicas o logarítmicas. En tercer año, todos los polinomios que les dan, cierran perfecto, asique no deberíamos preocuparnos por el CU "necesito esta ecuación que tiene raíces complejas", sino más bien "necesito esta ecuación con raíces reales, pero me equivoqué al tipear y dio que tiene complejas entonces no la resuelve". Me explico ?

**Comment by mariana13193** [comment]
@ezebor @Zaxtor Estoy haciendo pruebas con ejercicios sacados de una web de educación y hay ejemplos así , en cuyo caso la respuesta que ponen es " No hay solución". Algo así deberíamos mostrar, aunque sea para que no explote el Resolutor jajajajaja

**Comment by ezebor** [comment]
@mariana13193 @Zaxtor sisi, +1 a decir "no hay solución". Lo que puede pasar también, es que encuentre alguna solución, y depsués no haya más, por ejemplo: X^3-1=0.
