### ISSUE TITLE
Rompiending When ecuacion.... x = 5

### ISSUE THREAD

**Issue by leacoder** [agustinsilva/profebot#13]
![image](https://user-images.githubusercontent.com/4481229/45462782-b5459a80-b6df-11e8-840a-39162f737e24.png)

**Comment by ezebor** [comment]
El problema se debe a que la ecuación ingresada ya está resuelta (x = 5), razón por la cual, el backend devuelve 0 pasos de resolución. Voy a hacer lo mismo que con polinomios: cuando se ingresa algo ya resuelto, muestra directamente el pop up, y el botón atrás te lleva al ingreso nuevamente de ecuaciones

**Comment by ezebor** [comment]
Solved
