### ISSUE TITLE
La explicación no corresponde con el paso realizado 

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#15]
![screenshot_20180912-232025_profebot](https://user-images.githubusercontent.com/7290269/45463468-a57b8580-b6e2-11e8-917e-7f7694b5cbe2.jpg)

**Comment by Zaxtor** [comment]
No estoy seguro de esto, desde el back los pasos que se generan son:

ADD_POLYNOMIAL_TERMS, newEquation=1000001X=2
DIVIDE_FROM_BOTH_SIDES, newEquation=1000001X/1000001=2/1000001
SIMPLIFY_FRACTION, newEquation=X=2/1000001

Pareciera que esta explicando el paso 2, no? El tema es que recién se mostraría la resolución en el siguiente paso?

**Comment by Zaxtor** [comment]
@mariana13193  Es como te decía? Digamos, esta bien asi?

**Comment by ezebor** [comment]
@Zaxtor @mariana13193 ese texto se despliega ante la constante PASAJE_DE_TERMINO_DE_PRIMER_ANCESTRO_MULTIPLICACION_COMO_MULTIPLICACION. Capaz lo que está mal, es la asignación de la opción correcta. Es decir, está reconociendo una incorrecta, como si fuera correcta.

**Comment by mariana13193** [comment]
El issue está resuelto pero me crashea con el mismo ejemplo:
![image](https://user-images.githubusercontent.com/7290269/45581764-83b50680-b87a-11e8-9f82-58445f150a91.png)

**Comment by ezebor** [comment]
@mariana13193 lo de que pincha, ya está resuelto:

<img width="294" alt="captura de pantalla 2018-09-19 a la s 00 15 16" src="https://user-images.githubusercontent.com/11467605/45729061-27ffbb80-bba1-11e8-9932-98dfec350ddd.png">

Lo del texto, aun sigue mostrando un texto mal

**Comment by ezebor** [comment]
@Zaxtor el back mepa que manda mal la ubicación de los textos:

<img width="982" alt="captura de pantalla 2018-09-19 a la s 00 38 06" src="https://user-images.githubusercontent.com/11467605/45729772-6f3b7b80-bba4-11e8-9c91-34553c13ba64.png">

Lo probé para la ecuación 100x+x=2, siendo la captura el primer paso
