### ISSUE TITLE
Factoreo de polinomios - Factorear vacio error

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#17]
Ingresar un polinomio vacio produce que la aplicación crashee.
![image](https://user-images.githubusercontent.com/5430214/45464337-85e65c00-b6e6-11e8-8e29-38000e2d663f.png)

![image](https://user-images.githubusercontent.com/5430214/45464351-9a2a5900-b6e6-11e8-989f-c16aab9079fc.png)

![image](https://user-images.githubusercontent.com/5430214/45464398-c5ad4380-b6e6-11e8-800e-19043cd8b6a9.png)

**Comment by ezebor** [comment]
Solved
