### ISSUE TITLE
Cámara de Polinomios: no me muestra la ecuacion correcta :@

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#18]
![20180912_234813](https://user-images.githubusercontent.com/7290269/45464416-de1d5e00-b6e6-11e8-919b-35703af8ab60.jpg)
![screenshot_20180912-234834_profebot](https://user-images.githubusercontent.com/7290269/45464419-e2e21200-b6e6-11e8-9c6a-aa72854bbce0.jpg)

**Comment by ezebor** [comment]
acá me parece que la cámara no reconoció el término intermedio del polinomio, porque veo que el término independiente y el cuadrático los tomó bien (no me imagino porqué).

@mariana13193 probaste con otro polinomio cuadrático ?

**Comment by leacoder** [comment]
Aca el tema es que, hay 2 terminos con el mismo exponente. Y no me llego el caso de negocio de esto jaja.

Deberia hacer que se sumen, como esta en la pantalla de ingreso de terminos de polinomios.
