### ISSUE TITLE
Falta signo de error o correcto en paso terminado.

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#2]
En un paso ya resuelto de una ecuacion, no aparece el signo de correcto o error.
![image](https://user-images.githubusercontent.com/5430214/45392722-10539080-b5ff-11e8-8478-66fc494ddb41.png)

**Comment by ezebor** [comment]
el problema era que el texto era demasiado largo. Ajusté los componentes para que el texto sea multiline

<img width="302" alt="captura de pantalla 2018-09-12 a la s 19 44 33" src="https://user-images.githubusercontent.com/11467605/45457234-5fafc480-b6c4-11e8-8c50-5b3aa13ab43a.png">
