### ISSUE TITLE
Ecuaciones/Inec: foto de 3=3

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#20]
![image](https://user-images.githubusercontent.com/7290269/45464677-14a7a880-b6e8-11e8-8beb-842daa981a92.png)

**Comment by leacoder** [comment]
che, esto deberia ser filtrado en la UI cuando se ingresa la ecuacion? pq es al pedo hacer 3 = 3... avisen

**Comment by Zaxtor** [comment]
El back esta respondiendo ante estos eventos, en el changetype de la ecuación dice:
// e.g. 2 = 2
STATEMENT_IS_TRUE("STATEMENT_IS_TRUE")
/ e.g. 2 = 3
STATEMENT_IS_FALSE("STATEMENT_IS_FALSE")

alcanza con esto @ezebor ?

Probé con la función X-X+3=3 y anduvo bien (estaba tirando este nullpointer).

Lo dejo para chequear pero en principio estaría.

**Comment by ezebor** [comment]
Me llevo probarlo
