### ISSUE TITLE
Camara polinomios: Input con termino =

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#21]
Al sacarle una foto con la camara a un signo = , no indica que es un polinomio invalido. Lo procesa con otro valor.

![image](https://user-images.githubusercontent.com/5430214/45464702-29843c00-b6e8-11e8-90de-a43716363b88.png)

![image](https://user-images.githubusercontent.com/5430214/45464693-1d987a00-b6e8-11e8-9c3e-4eca43b81d49.png)

**Comment by leacoder** [comment]
No puedo reproducir el bug, escanie varios signos = .
Uno me lo tomo como un T y tiro mensaje de error.
Otro me dijo que era un 2/2 y tmb dio mensaje de error diciendo q no era un polinomio.

**Comment by leacoder** [comment]
Fixed, agrege un checkeo para las constantes, en una oportunidad escaneando el igual me devolvio una constante, y agregue ese checkeo, ya que un polinomio necesita terminos con X.
