### ISSUE TITLE
Factoreo de polinomios no finaliza.

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#22]
Sigue figurando el factoreo de un nuevo paso sin finalizar el proceso de multiplechoice:
![image](https://user-images.githubusercontent.com/5430214/45494925-86174380-b748-11e8-9c9d-b2e917c58f16.png)

**Comment by ezebor** [comment]
Solved. El problema era que se reconocía a gauss como método correcto, pero en realidad no se puede porque no tiene raíces reales
