### ISSUE TITLE
Ecuaciones: llego hasta el paso 8 y no me deja continuar, ni ver Resumen. El ejercicio es -6X+4=15X

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#23]
![screenshot_20180915-003626_profebot](https://user-images.githubusercontent.com/7290269/45582053-a695e980-b87f-11e8-9b22-dffe2ceee191.jpg)

**Comment by mariana13193** [comment]
**Me pasa lo mismo cuando resuelvo la ecuacion (9x-7)/8 = -1 
Es como que llega hasta el paso 8 y muere ahi siempre.**

![screenshot_20180915-011321_profebot](https://user-images.githubusercontent.com/7290269/45582357-bebc3780-b884-11e8-8306-07d4effa8047.jpg)

**Comment by ezebor** [comment]
Done:

Muestro para el ejemplo -6X+4=15X que llego hasta el paso 9 (último):

<img width="287" alt="captura de pantalla 2018-09-17 a la s 03 34 01" src="https://user-images.githubusercontent.com/11467605/45608675-9a9a5b00-ba2a-11e8-831c-b47e4c764fd7.png">

@mariana13193 sin embargo, si resolves el paso 9, va a explotar, por un problema del backend que repercute en el front. Ese problema ya lo cargué como issue, se lo comenté a samu, y lo taggié como backend.

**Comment by mariana13193** [comment]
Estaba resolviendo este mismo ejercicio y crasheó:
![image](https://user-images.githubusercontent.com/7290269/45620779-58860f00-ba54-11e8-8a8c-dfbc04e31231.png)

**Comment by mariana13193** [comment]
@ezebor ok!! Si, me crasheó a mi tambienn!
