### ISSUE TITLE
No scrollea automáticamente hasta el último paso generado para resolver

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#24]
Esto me pasa cuando se generan varios pasos (más de 4 o 5). Por ejemplo, me genera el paso 5, pero el scroll de la pantalla me muestra hasta el paso 3 y tengo que ir scrolleando hasta el final.

**Comment by ezebor** [comment]
Done. Fix: se listan al reves. Es decir, cada paso nuevo, se pone arriba de todo, y el scroll se hace automáticamente hasta arriba.

@mariana13193 hay una excepción: para el paso 2, siempre hay que scrollear un poquito hacia arriba, porque lo que pasa al principio, es que el componente del front no está "completo" al principio, por eso es como que se rellena con los dos primeros pasos. Ya a partir del 3ero inclusive, se scrollea siempre al tope automáticamente

**Comment by mariana13193** [comment]
@ezebor Probado. Tambien me hace scrollear en el paso 3, a partir del 4 me funciona bien. Pero cerramos el issue acá hasta nuevo aviso (?
