### ISSUE TITLE
Multiple Choice: No muestra las ecuaciones completas cuando son muy largas

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#25]
![screenshot_20180915-004647_profebot](https://user-images.githubusercontent.com/7290269/45582132-05a82e00-b881-11e8-83cb-849ed0262535.jpg)

**Comment by ezebor** [comment]
Done

<img width="306" alt="captura de pantalla 2018-09-17 a la s 03 37 06" src="https://user-images.githubusercontent.com/11467605/45608745-f95fd480-ba2a-11e8-80b9-e2f533e98920.png">
