### ISSUE TITLE
El paso de Realizar Distributiva explota :S

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#26]
El ejercicio que ingresé es 2x´2-6x=0
![screenshot_20180915-005000_profebot](https://user-images.githubusercontent.com/7290269/45582160-86672a00-b881-11e8-9bbb-45f1326925cd.jpg)

**Comment by ezebor** [comment]
Creo que este issue es el mismo que cargué [acá](https://github.com/agustinsilva/profebot/issues/40)

**Comment by agustinsilva** [comment]
El issue esta resuelto:
![image](https://user-images.githubusercontent.com/5430214/45730709-a7918880-bba9-11e8-81f7-78372f9652ea.png)

![image](https://user-images.githubusercontent.com/5430214/45730711-ae200000-bba9-11e8-89e6-d15c9d05bede.png)

![image](https://user-images.githubusercontent.com/5430214/45730716-b4ae7780-bba9-11e8-982d-ed7f84b66b70.png)
