### ISSUE TITLE
Cám en Polinomios no parsea 

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#27]
![20180915_005914](https://user-images.githubusercontent.com/7290269/45582292-79e3d100-b883-11e8-8eb9-0dc06d19ba76.jpg)
![screenshot_20180915-005623_profebot](https://user-images.githubusercontent.com/7290269/45582210-52403900-b882-11e8-9473-8f43ee91e180.jpg)

**Comment by leacoder** [comment]
Ya encontre el problem, mañana lo fixeo
