### ISSUE TITLE
Error cuando parsea ecuación con () y fraccion

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#28]
![screenshot_20180915-011633_profebot](https://user-images.githubusercontent.com/7290269/45582392-69345a80-b885-11e8-8a9c-7b902edc64a7.jpg)
![screenshot_20180915-011801_profebot](https://user-images.githubusercontent.com/7290269/45582393-6c2f4b00-b885-11e8-84d8-5a0a55564c3c.jpg)

**Comment by leacoder** [comment]
fixeado, mas vale que llames a trump para testear este bug

**Comment by mariana13193** [comment]
A Trump no le funca

![image](https://user-images.githubusercontent.com/7290269/45597649-d9d29880-b9a5-11e8-8001-cb7f446ce37b.png)

**Comment by leacoder** [comment]
No le funco a Trump pq eze me cago el funcionamiento de la camara en un commit, volve a probarlo =D

**Comment by mariana13193** [comment]
**@Zaxtor @agustinsilva Ahora rompe pero en el Resolutor, entiendo que tiene que ver con el TODO que tenemos!**

![image](https://user-images.githubusercontent.com/7290269/45602061-9439be00-b9ed-11e8-8d83-d00c0b9c6f10.png)

**Comment by mariana13193** [comment]
Lo damos por cerrado, aunque quedo media feucha la ecuación, pero en teoría está ok asi:

![screenshot_20180922-003534_profebot](https://user-images.githubusercontent.com/7290269/45912904-9772e680-bdff-11e8-949d-484126f42996.jpg)
