### ISSUE TITLE
Crash Resolutor

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#29]
**Ingresé con pizarra la ecuación (9x-7) 1/8 = -1/3x**
![image](https://user-images.githubusercontent.com/7290269/45582416-d2b46900-b885-11e8-958c-ee1713e2bc67.png)

**Comment by Zaxtor** [comment]
Si Marian, ese error en particular es del front, le cambio el tag!

**Comment by ezebor** [comment]
@mariana13193 @Zaxtor chicxs, aparentemente es de backend, porque esa misma ecuación la testié con el parser a latex del front, y dio bien:

<img width="1400" alt="captura de pantalla 2018-10-08 a la s 19 20 10" src="https://user-images.githubusercontent.com/11467605/46636660-4cf7a680-cb2f-11e8-9562-e14a9404b30e.png">

Es decir, para el front no es una expresión inválida. Además de eso, el error que me salta es del Tree:

ERROR: Unable to start activity ComponentInfo{ar.com.profebot/ar.com.profebot.activities.SolveEquationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Integer ar.com.profebot.parser.container.TreeNode.getIntegerValue()' on a null object reference

**Comment by Zaxtor** [comment]
@ezebor  Lo que tira error no es la primer ecuación, es una de las que resuelve, creería que es (según la imagen de Marian):

((9*X-7)*1)/X=(-1/3)*8

Esa la parsea bien? En el error que reporta Marian, el trace indica que lo tira el front, no entendi lo del null que decias del tree, puede ser que te tire error en el watch porque no se esta usando como se espera o algo asi.
