### ISSUE TITLE
Raices del polinomio factoreado

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#30]
![image](https://user-images.githubusercontent.com/7290269/45582490-705c6800-b887-11e8-8579-1d098e3b1fed.png)

**Comment by mariana13193** [comment]
**Este es el polinomio y el paso previo a que explote todooooooo:**
![20180915_013433](https://user-images.githubusercontent.com/7290269/45582553-89194d80-b888-11e8-97d9-4b32d0cb0b26.jpg)
![screenshot_20180915-013523_profebot](https://user-images.githubusercontent.com/7290269/45582554-8c143e00-b888-11e8-8b7f-4fcd58bdb277.jpg)

**Comment by mariana13193** [comment]
Idem con:

![screenshot_20180915-015747_profebot](https://user-images.githubusercontent.com/7290269/45582711-24abbd80-b88b-11e8-8b14-30e067b43c3a.jpg)

**Comment by ezebor** [comment]
@mariana13193 esto en realidad es en ecuaciones/inecuaciones no ? Porque me imagino cual es el problema. Cuando hay más de una raíz, el back no me devuelve algo que se pueda mostrar en el "nuevo paso", tonces por eso explota.

**Comment by mariana13193** [comment]
@ezebor si! Es en Ecuaciones/inec

**Comment by ezebor** [comment]
@mariana13193 debería estar fixed:

* Primer caso: 
<img width="291" alt="captura de pantalla 2018-09-15 a la s 16 48 59" src="https://user-images.githubusercontent.com/11467605/45590091-86aa0880-b907-11e8-8577-4c0c63a63624.png">
<img width="288" alt="captura de pantalla 2018-09-15 a la s 16 48 55" src="https://user-images.githubusercontent.com/11467605/45590092-86aa0880-b907-11e8-9045-96f79b68ddc4.png">

* Segundo caso:
<img width="301" alt="captura de pantalla 2018-09-15 a la s 16 50 17" src="https://user-images.githubusercontent.com/11467605/45590098-90337080-b907-11e8-8e49-eeb6fd8f6153.png">
