### ISSUE TITLE
App crash al terminar de resolver

### ISSUE THREAD

**Issue by Zaxtor** [agustinsilva/profebot#32]
Dada la ecuación:

**2+X=5**

eligiendo las 2 primeras invalidas y la ultima correcta, arroja el siguiente error:

![image](https://user-images.githubusercontent.com/906674/45589645-a2a9ac00-b8ff-11e8-9060-653469873b29.png)

Y cierra la app.

**Comment by ezebor** [comment]
Solved

<img width="298" alt="captura de pantalla 2018-09-17 a la s 16 07 34" src="https://user-images.githubusercontent.com/11467605/45644317-dae1f380-ba93-11e8-8cc8-b7e2b2caeeae.png">
