### ISSUE TITLE
No se visualiza el factoreo completo en resumen

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#35]
La expresión factorizada se ve incompleta en el resumen.
![image](https://user-images.githubusercontent.com/5430214/45590481-64b48400-b90f-11e8-9094-9419d3ad2111.png)

**Comment by ezebor** [comment]
Solved

<img width="291" alt="captura de pantalla 2018-09-18 a la s 23 16 03" src="https://user-images.githubusercontent.com/11467605/45727176-dfdc9b00-bb98-11e8-8e97-e06a7db3a313.png">

**Comment by agustinsilva** [comment]
El issue se sigue dando:
![image](https://user-images.githubusercontent.com/5430214/45729437-d35d4000-bba2-11e8-83c5-6cdf293bd056.png)

**Comment by ezebor** [comment]
@agustinsilva tenés todo pulleado no ? si la rta es si, entonces puede ser la resolución, aunque medio raro, porque debiera adaptarse, como en otros casos. Lo checkeo

**Comment by agustinsilva** [comment]
Si, volvi a pullear a ver si era mi version, pero sigue pasando al menos en mi telefono.

**Comment by ezebor** [comment]
@agustinsilva ahora si debería estar, lo probé en un celular de resolución menor:

<img width="280" alt="captura de pantalla 2018-10-08 a la s 18 56 24" src="https://user-images.githubusercontent.com/11467605/46635819-140a0280-cb2c-11e8-8261-2d45fe80cec0.png">
