### ISSUE TITLE
Resolutor: java.lang.Error: No term with symbol: X

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#36]
![image](https://user-images.githubusercontent.com/7290269/45602492-bfc0a680-b9f5-11e8-9311-685b600f8e20.png)

![image](https://user-images.githubusercontent.com/7290269/45602489-b59ea800-b9f5-11e8-8fb3-7edf83ae48c4.png)

**Comment by ezebor** [comment]
Eso puede pasar porque se ingresó con minúscula, y el Tree pide mayúscula. BTW, eso está validado (se supone) en todos lados. Desde donde llegó esa ecuación ? @mariana13193

**Comment by mariana13193** [comment]
@ezebor @Zaxtor No pasa más el error reportado, pero me hace ruido que el nuevo paso sea igual que el ejercicio ingresado:

![screenshot_20180922-002700_profebot](https://user-images.githubusercontent.com/7290269/45912833-58906100-bdfe-11e8-9668-9cadbf2ccd8e.jpg)

**Comment by Zaxtor** [comment]
Lo que detectaste marian esta solucionado, ahora muestra mejor detalle de lo que hace (lo estaba distribuyendo y lo volvía a factorear, por eso te mostraba que el siguiente paso era el mismo).

Por otro lado, continua el problema de cuadráticas con raíces reales (no enteras).. Deberíamos crear otro issue para esto, para definir si lo ignoramos o hacemos un refactor del código.
