### ISSUE TITLE
Foto de inecuación mal parseada

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#37]
![image](https://user-images.githubusercontent.com/7290269/45602616-a91b4f00-b9f7-11e8-80d0-c67715e6f648.png)

![screenshot_20180916-213006_profebot](https://user-images.githubusercontent.com/7290269/45602634-eed81780-b9f7-11e8-97c5-c618e2f41fe6.jpg)

**Comment by ezebor** [comment]
Solved 

![screenshot_20180918-141855](https://user-images.githubusercontent.com/11467605/45705328-b0ee0700-bb4f-11e8-9517-88b4d841137e.png)

**Comment by mariana13193** [comment]
Funciona el parseo, pero rompe cuando lo quiero resolver:

![image](https://user-images.githubusercontent.com/7290269/45720844-2a035380-bb7c-11e8-906c-4353e6b89f86.png)

**Comment by EzequielBorenstein** [comment]
@mariana13193 si, eso está en el otro issue que cargué de backend ([este](https://github.com/agustinsilva/profebot/issues/40)). De todas formas, este issue era sobre el parseo, cosa que está resuelta. Cerremos este, y seguimos lo de la resolución en los otros issues cargados
