### ISSUE TITLE
Backend devuelve expresión con notación polaca

### ISSUE THREAD

**Issue by ezebor** [agustinsilva/profebot#41]
Ingreso por pizarra:

<img width="559" alt="captura de pantalla 2018-09-18 a la s 14 46 22" src="https://user-images.githubusercontent.com/11467605/45706085-bd735f00-bb51-11e8-9fbb-b9c1219bbe6d.png">

Al ir al MC, explota por lo siguiente:

<img width="670" alt="captura de pantalla 2018-09-18 a la s 14 45 43" src="https://user-images.githubusercontent.com/11467605/45706110-c9f7b780-bb51-11e8-85f2-ecf1b3af9557.png">

Por alguna razón, devuelve el "*" al principio, en vez de hacerlo en forma infija. Ese string es el que consumo directamente del MultipleChoiceStep

**Comment by Zaxtor** [comment]
Resuelto junto con la anterior, estaba resolviendo mal la distributiva.
