### ISSUE TITLE
Valor entero con coma en Pasos de Factoreo de polinomios

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#42]
En los pasos de factoreo, figura el entero con coma.
![image](https://user-images.githubusercontent.com/5430214/45720763-d4c74200-bb7b-11e8-8d92-4671580a592e.png)

En el resumen figura el valor sin coma.
![image](https://user-images.githubusercontent.com/5430214/45720772-dc86e680-bb7b-11e8-8775-369dbec2a034.png)

**Comment by ezebor** [comment]
Solved

<img width="289" alt="captura de pantalla 2018-09-19 a la s 00 42 26" src="https://user-images.githubusercontent.com/11467605/45729853-e709a600-bba4-11e8-9003-a2ebf8a8290f.png">
