### ISSUE TITLE
Resolviendo Ecuacion 14x+(19x+18)=1

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#43]
![image](https://user-images.githubusercontent.com/7290269/45720930-8c5c5400-bb7c-11e8-9219-462ea051ffaf.png)

**Comment by ezebor** [comment]
Chicos, este issue es del back: el back manda la front ecuaciones mal escritos sintácticamente:

<img width="794" alt="captura de pantalla 2018-09-18 a la s 23 54 34" src="https://user-images.githubusercontent.com/11467605/45728432-6051ca80-bb9e-11e8-817b-5f035e949824.png">

No se deberían poder escribir dos operadores juntos (es decir: `*-`), habría que generar un par de paréntesis, porque sino, al pasarlo a latex explota. En el front se podría validar, pero es bastante más complejo, es más fácil que desde el back se genere ya con paréntesis. Doy algunos ejemplos extra:

1^-2 --> 1^(-2)
1*-2 --> 1*(-2)
1/-2 --> 1/(-2)

**Comment by Zaxtor** [comment]
Ahora envuelve entre paréntesis, pero sigue tirando error de parseo!

**Comment by ezebor** [comment]
Resuelto

<img width="298" alt="captura de pantalla 2018-10-08 a la s 19 26 58" src="https://user-images.githubusercontent.com/11467605/46636871-2c7c1c00-cb30-11e8-818b-99972f30bc2b.png">
<img width="298" alt="captura de pantalla 2018-10-08 a la s 19 27 06" src="https://user-images.githubusercontent.com/11467605/46636872-2c7c1c00-cb30-11e8-8227-25d690c2800f.png">
