### ISSUE TITLE
Resolviendo Polinomio

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#45]
Ingresandolo a mano...
![image](https://user-images.githubusercontent.com/7290269/45721835-06420c80-bb80-11e8-89aa-ac5812cb87c2.png)

![image](https://user-images.githubusercontent.com/7290269/45721722-9f245800-bb7f-11e8-8998-1c049675f2fb.png)

**Comment by ezebor** [comment]
[Duplicated: https://github.com/agustinsilva/profebot/issues/44]
