### ISSUE TITLE
Usando el botón Goma en polinomios (con varios términos)

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#46]
![image](https://user-images.githubusercontent.com/7290269/45721918-72bd0b80-bb80-11e8-9909-73b8d67de510.png)
![screenshot_20180918-202336_profebot](https://user-images.githubusercontent.com/7290269/45722008-d7786600-bb80-11e8-9fb7-50cb1570f007.jpg)

**Comment by ezebor** [comment]
@mariana13193 no tenrás el polinomio del que empezaste a borrar ?

**Comment by mariana13193** [comment]
@ezebor mm era con cualquiera que ingresaba varios términos, e intentaba borrar

**Comment by ezebor** [comment]
Resuelto
