### ISSUE TITLE
Crash al borrar un ejercicio pendiente

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#47]
![image](https://user-images.githubusercontent.com/7290269/45729063-2930e880-bba1-11e8-9de9-275ca4bb6719.png)

**Comment by mariana13193** [comment]
Creo que no es al borrar, sino al mantener presionado algún ejercicio de los pendientes!

**Comment by EzequielBorenstein** [comment]
@mariana13193 ya se lo que es... diooos, odio esa función jajaja lo bueno es que le puse testing unitario, asique cuando arregle esto, voy a estar seguro de que no la cagué en los demás

**Comment by ezebor** [comment]
@mariana13193 debería estar solved
