### ISSUE TITLE
Error al seleccionar opcion incorrecta en paso de inecuacion x + 5 < x +1

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#49]
Al seleccionar una opcion incorrecta en la inecuacion x + 5 < x + 1, la aplicacion falla.
![image](https://user-images.githubusercontent.com/5430214/45730201-c2163280-bba6-11e8-80c2-4da5a26173d6.png)

El log es el siguiente:
![image](https://user-images.githubusercontent.com/5430214/45730136-6f3c7b00-bba6-11e8-9818-e65a671f72dd.png)

**Comment by Zaxtor** [comment]
Esto también es front, si ya muestra la lista de pasos, todo lo que pasa después es front.

**Comment by ezebor** [comment]
Resuelto

<img width="305" alt="captura de pantalla 2018-10-08 a la s 20 32 59" src="https://user-images.githubusercontent.com/11467605/46638867-6140a100-cb39-11e8-9e49-74bb2c096cd9.png">
