### ISSUE TITLE
Error al seleccionar un ejercicio pendiente

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#50]
Al seleccionar un ejercicio pendiente cualquiera, la aplicación se reinicia.
El log es el siguiente:
![image](https://user-images.githubusercontent.com/5430214/45730334-6ef0af80-bba7-11e8-8dd5-db6471bbe0f2.png)

**Comment by Zaxtor** [comment]
Cambio de etiqueta, tiene pinta de front..

**Comment by ezebor** [comment]
Solved

<img width="305" alt="captura de pantalla 2018-09-21 a la s 16 07 37" src="https://user-images.githubusercontent.com/11467605/45901229-99658700-bdb8-11e8-96a5-19352594aca0.png">
