### ISSUE TITLE
Falta información en Resumen de ecuación resuelta

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#51]
En el resumen de ecuación falta información respecto a como queda el resultado final.

![image](https://user-images.githubusercontent.com/5430214/45730531-9bf19200-bba8-11e8-942c-c0ba3d89089c.png)

**Comment by ezebor** [comment]
Resuelto

<img width="287" alt="captura de pantalla 2018-10-08 a la s 20 30 06" src="https://user-images.githubusercontent.com/11467605/46638794-fbecb000-cb38-11e8-8bcc-f55cf89b6c6f.png">
