### ISSUE TITLE
Modificar Textos

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#53]
En los botones se podria poner: "Próximo paso" y "Quiero saber más"
![screenshot_20181006-172039_profebot](https://user-images.githubusercontent.com/7290269/46575572-20585900-c98e-11e8-8446-09e3ce34d20e.jpg)
![screenshot_20181006-172021_profebot](https://user-images.githubusercontent.com/7290269/46575573-20585900-c98e-11e8-8f67-9d35384fb93c.jpg)

**Comment by ezebor** [comment]
Resuelto

<img width="292" alt="captura de pantalla 2018-10-08 a la s 21 44 52" src="https://user-images.githubusercontent.com/11467605/46640606-73274180-cb43-11e8-811c-216a32042e4b.png">
<img width="303" alt="captura de pantalla 2018-10-08 a la s 21 44 57" src="https://user-images.githubusercontent.com/11467605/46640607-73274180-cb43-11e8-8f0d-b271877af67e.png">
