### ISSUE TITLE
No puedo VER RESUMEN ni elegir el PASO

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#54]
La inecuacion que ingresé por pizarra: 3(x-1)+2x<x+1
![screenshot_20181006-174003_profebot](https://user-images.githubusercontent.com/7290269/46575624-0408ec00-c98f-11e8-8354-57c5f8d74af4.jpg)

**Comment by ezebor** [comment]
Resuelto

<img width="292" alt="captura de pantalla 2018-10-08 a la s 19 34 19" src="https://user-images.githubusercontent.com/11467605/46637154-40744d80-cb31-11e8-9ad5-40594237adbc.png">
<img width="292" alt="captura de pantalla 2018-10-08 a la s 19 34 52" src="https://user-images.githubusercontent.com/11467605/46637155-410ce400-cb31-11e8-9667-ab404f983e14.png">
