### ISSUE TITLE
Ingreso Polinomios manual: no desaparecer cuando se ingresa 1

### ISSUE THREAD

**Issue by mariana13193** [agustinsilva/profebot#61]

**Comment by ezebor** [comment]
Resuelto

<img width="301" alt="captura de pantalla 2018-10-20 a la s 16 49 51" src="https://user-images.githubusercontent.com/11467605/47259935-3420b680-d488-11e8-9a77-bf74fcb65588.png">
<img width="295" alt="captura de pantalla 2018-10-20 a la s 16 49 56" src="https://user-images.githubusercontent.com/11467605/47259936-35ea7a00-d488-11e8-9b64-006cadf0f74a.png">
