### ISSUE TITLE
Boton de resumen sin funcionalidad en Ecuaciones/inecuaciones

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#8]
El boton que figura en la pantalla de resolucion de ecuaciones/inecuaciones no tiene funcionalidad.

![image](https://user-images.githubusercontent.com/5430214/45393348-e354ad00-b601-11e8-94ba-379f1433e7f6.png)

**Comment by ezebor** [comment]
Faltan mostrar las raíces, pero la funcionalidad del botón ya está hecha.
