### ISSUE TITLE
Texto erroneo en Ver resumen de ecuaciones / inecuaciones

### ISSUE THREAD

**Issue by agustinsilva** [agustinsilva/profebot#9]
Ver resumen en ecuaciones / inecuaciones indica como titulo:
"Factoreo terminado" y unicamente muestra la ecuacion inicial.
![image](https://user-images.githubusercontent.com/5430214/45461220-21240500-b6d8-11e8-916a-dfbaff4496cf.png)

![image](https://user-images.githubusercontent.com/5430214/45461235-3731c580-b6d8-11e8-830f-4c42aa42416f.png)

**Comment by ezebor** [comment]
El título de "factoreo terminado" ya está corregido. Lo de las raíces, falta definir con el back como se manejan las raíces cuadráticas, y los casos en los cuales no existen raíces o existen infinitas
